# root 

GET http://localhost:3000/
###
GET http://localhost:3000/filter?color=green
###
GET http://localhost:3000/filter?quantity=3
###
GET http://localhost:3000/format
###
GET http://localhost:3000/maxcost
###
GET http://localhost:3000/getsalecallback
###
GET http://localhost:3000/getsalepromise
###
GET http://localhost:3000/getsaleasync
###
POST http://localhost:3000/switchsource
###

GET http://localhost:3000/getfiles
###
POST http://localhost:3000/optimize HTTP/1.1
content-type: application/json

{"filename": "prod.json"}
###

# post

POST http://localhost:3000/edit HTTP/1.1
content-type: application/json

[
  {"type":"socks","color":"red","quantity":10,"priceForPair":"$3"},
  {"type":"socks","color":"green","quantity":5,"priceForPair":"$10"},
  {"type":"socks","color":"blue","quantity":8,"priceForPair":"$6"},
  {"type":"hat","color":"red","quantity":7,"price":"$5"},
  {"type":"hat","color":"blue","quantity":0,"price":"$6"},
  {"type":"socks","color":"blue","priceForPair":"$6"},
  {"type":"socks","color":"green","quantity":10,"priceForPair":"$30"},
  {"type":"socks","color":"white","quantity":3,"priceForPair":"$4"},
  {"type":"socks","color":"blue","priceForPair":"$10"},
  {"type":"socks","color":"green","quantity":2,"priceForPair":"$6"},
  {"type":"hat","color":"blue","quantity":3,"price":"$5"},
  {"type":"hat","color":"red","quantity":1,"price":"$6"},
  {"type":"socks","color":"blue","priceForPair":"$6"}
]
###